---
# Non-secret configuration for the Taiga deployment

taiga_domain: "ulasovets.de"
taiga_sites_scheme: "http"
taiga_admin_email: "ulasovetsvladimir@gmail.com"
taiga_admin_username: "admin"
taiga_db_name: "taiga"
taiga_db_user: "taiga"
enable_ssl: false
letsencrypt_email: "ulasovetsvladimir@gmail.com"
